#spring.datasource.url=jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE:serverdb}?createDatabaseIfNotExist=true
#spring.datasource.username=finley
#spring.datasource.password=Vi030819!
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
#
## Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.main.allow-circular-references=true
#spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

spring:
  datasource:
    password: samuel267
    url: jdbc:mysql://database-1.cgdqufqivqcu.us-east-1.rds.amazonaws.com:3306/serverdb?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

